---
apiVersion: cluster.ipfs.io/v1alpha1
kind: IpfsCluster
metadata:
  name: cluster-1
spec:
  clusterStorage: 1Gi
  ipfsStorage: 2Gi
  public: false 
  replicas: 1
  networking:
    circuitRelays: 1
  ipfsResources:
    limits:
      cpu: 250m
      memory: 700M
  follows:
  - name: gutenberg_es
    template: gutenberg-es.collab.ipfscluster.io 
