
---
apiVersion: cluster.ipfs.io/v1alpha1
kind: Ipfs
metadata:
  name: ipfs-sample-collab
spec:
  url: apps.jephilli-4-11-04-28-0655.devcluster.openshift.com 
  ipfsStorage: 2Gi
  clusterStorage: 1Gi
  public: true
  replicas: 1
  networking:
    circuitRelays: 1
  follows:
  - name: gutenberg_es
    template: gutenberg-es.collab.ipfscluster.io 