---
apiVersion: cluster.ipfs.io/v1alpha1
kind: Ipfs
metadata:
  name: ipfs-sample
spec:
  url: apps.jephilli-4-11-04-28-0655.devcluster.openshift.com 
  ipfsStorage: 50Gi
  clusterStorage: 5Gi
  public: true
  replicas: 2
  follows: []
  networking:
    circuitRelays: 2
